### ISSUE TITLE
RETAIN ignored on Windows platforms

### ISSUE THREAD

**Issue by jgoehringer** [pm2-hive/pm2-logrotate#56]
The determination of the variable fileBaseName (line 65) depends on forward slash being the path separator. Tested using path.sep instead of '/'; yields expected results.

**Comment by maxime-helen-sb** [comment]
Same for me. Would it be possible to have this fix to master? I don't know how to ask pm2 to use my own branch/fork of log rotate a plugin. I tried to create a PR but I have no permissions as expected.

**Comment by NitayRabi** [comment]
Same Here. - logs are never deleted, seems to retain an infinite amount of files over time.

**Comment by cuteboi** [comment]
Same here, on FreeBSD, but I'm getting an error as well.  I'll create a new report for that.

**Comment by NoorAbdulhameed** [comment]
This issue is produced on "pm2-logrotate@2.7.0", in app.js file the "path.sep" is not used; instated the code still uses the forward slash '/' which does not work on Windows

** I used "pm2 install pm2-logrotate" to install the module on PM2 and the "retain" config did not work, log files just kept piling beyond the value of "retain", when I checked the app.js file under pm2-logrotate, the file still uses the '/' separator, the below code snippet taken from the app.js file:

` var fileBaseName = file.substr(0, file.length - 4).split(**'/'**).pop() + "__"; `

hence the fix in #111 does not apply to version @2.7.0 

is the pull request #154 planned to be merged to version 2.7.0 any time soon as it should fix the issue?

**Comment by Karrlllis** [comment]
Hi

Is there plan to merge in fix?

**Comment by mycharoka** [comment]
does the log keep on piling up even with retain being set?

**Comment by PLCs7** [comment]
Good morning,
I noticed that in the pm2-logrotate repository, the following line is still present in app.js:

var fileBaseName = file.substr(0, file.length - 4).split('/').pop() + "__";

Could you consider merging the proposed fix into the master branch to enable proper file deletion on Windows as well?

Thank you.
